FROM ubuntu:18.04

RUN apt-get update
RUN apt-get -y install build-essential python3
RUN apt-get -y install gcc-5 gcc-6 gcc-7 gcc-8 clang-4.0 clang-5.0 clang-6.0 \
  clang-7 clang-8 clang-9 clang-10

